[versions]
agp = "8.13.1"
kotlin = "2.0.20"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
lifecycleRuntimeKtx = "2.9.4"
activityCompose = "1.11.0"
composeBom = "2024.09.00"
kotlinxCoroutinesAndroid = "1.7.3"
material3 = "1.4.0"
room = "2.6.1"
ksp = "2.0.20-1.0.24"
roomCompiler = "2.8.3"
roomCommonJvm = "2.8.4"
desugar = "2.0.4"
roomKtx = "2.8.4"
amap = "9.8.0"
amap_search = "9.7.0 "
amap_location = "6.4.1"
playServicesMaps = "19.2.0"
runtime = "1.9.5"
composeMaterial = "1.5.5"
playServicesTagmanagerV4Impl = "18.1.1"


[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-material-icons-extended = {group = "androidx.compose.material", name = "material-icons-extended"}
org-jetbrains-kotlinx-kotlinx-coroutines-android = {group = "org-jetbrains-kotlinx", name = "kotlinx-coroutines-android",version.ref = "kotlinxCoroutinesAndroid" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
androidx-room-room-runtime ={group="androidx.room",name="room-runtime",version.ref="room"}
#androidx-room-room-ktx={group="androidx.room",name="room-ktx",version.ref="room"}
androidx-room-room-compiler = {group="androidx.room",name="room-compiler",version.ref="room"}
androidx-room-common-jvm = { group = "androidx.room", name = "room-common-jvm", version.ref = "roomCommonJvm" }
com-android-tools-desugar-jdk-libs ={group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "desugar"}
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "roomKtx" }
com-amap = {group = "com.amap.api",name = "3dmap",version.ref = "amap"}
com-amap-api-search = {group = "com.amap.api",name = "search",version.ref = "amap_search"}
com-amap-api-location = {group = "com.amap.api",name = "location",version.ref = "amap_location"}
play-services-maps = { group = "com.google.android.gms", name = "play-services-maps", version.ref = "playServicesMaps" }
androidx-compose-runtime = { group = "androidx.compose.runtime", name = "runtime", version.ref = "runtime" }
androidx-compose-material = { group = "androidx.wear.compose", name = "compose-material", version.ref = "composeMaterial" }
play-services-tagmanager-v4-impl = { group = "com.google.android.gms", name = "play-services-tagmanager-v4-impl", version.ref = "playServicesTagmanagerV4Impl" }



[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
ksp = { id= "com.google.devtools.ksp",version.ref="ksp" }  #用于 Room
